import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const SUIT = localFont({
  src: '../assets/fonts/SUIT-Variable-ttf/SUIT-Variable.ttf',
  variable: '--font-suit',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SUIT.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
