import type { Metadata } from "next";
import localFont from 'next/font/local'
import { UserProvider } from '@/lib/auth/userContext';
import { getUser } from "@/lib/db/queries";

import "./globals.css";

const SUIT = localFont({
  src: '../assets/fonts/SUIT-Variable-ttf/SUIT-Variable.ttf',
  variable: '--font-suit',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userPromise = getUser();

  return (
    <html lang="en">
      <UserProvider userPromise={userPromise}>
        <body
          className={`${SUIT.variable} antialiased bg-gray-50`}
        >
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
